meta_product_name: "GPS da Bari"
meta_title: "Bari GPS - Your guide through the bariatric journey"
meta_description: "An app that will help bariatric patients, by giving them options to track their progress in important aspects of living post-surgery. Users can track their weight, vitamin intake, choose personal goals and search for healthy meal recipes"
meta_image: "exemplo.png" # should exist in `app/assets/images/`
